options:
  max-time: 120

definitions:
  steps:
    - step: &setDefaults
        name: Setting defaults
        image: cypress/included:3.4.0
        artifacts:
          - cypress/videos/**
          - cypress/screenshots/**
          - cypress/report/**
    - step: &run_must_pass_batch1
        <<: *setDefaults
        name: run MUST tests in specs - batch1
        script:
          - npm install && npx cypress run --env sessionToken=${sessionToken},configFile=${environment} --spec=cypress/integration/testCases/*.spec.js
    - step: &run_specs
        <<: *setDefaults
        name: Run all tests in selected specs
        script:
          - npm install && npx cypress run --env sessionToken=${sessionToken},configFile=${environment} --spec=${commaSeparatedSpecPaths}
pipelines:
  custom:
    run_must_pass_tests_in_all_specs:
      - variables:
          - name: environment
            default: "tenable-prod"
          - name: sessionToken
            default: "specify-only-if-captcha-is-enabled"
      - step: *run_must_pass_batch1
    run_specs:
      - variables:
          - name: environment
            default: "tenable-prod"
          - name: sessionToken
            default: "specify-only-if-captcha-is-enabled"
          - name: commaSeparatedSpecPaths
            default: "cypress/integration/testCases/UI_002_DeleteRepoCloud.spec.js,cypress/integration/testCases/UI_003_ProjectCreateUpdateDelete.spec.js"
      - step: *run_specs
